---
- name: Instalar mariadb package 
  apt: name={{ item }} state=present 
  with_items: 
   - mariadb-server
#   - php-mysql
#   - python-mysqldb
   - python-mysqldb
#   - libselinux-python 
#   - libsemanage-python 

#- name: Configure SELinux to start mysql on any port 
#  seboolean: name=mysql_connect_any state=true persistent=yes 
#  when: ansible_selinux.status == "enabled" 

- name: Create mariadb configuration file 
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf 
  notify: 
  - restart mariadb 

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host=% state=present

- name: Start mariadb Service 
  service: name=mariadb state=started enabled=yes  
